### ISSUE TITLE
Flux Integration

### ISSUE THREAD

**Issue by kdiji** [mlkmhd/kubernetes-security-policies#1]
Just curious if this project can be used with Flux . I Just tested it by just adding a `simple-pod.yaml` :
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default # should fail in rego check
spec:
  containers:
  - name: nginx
    image: nginx:latest # should fail in rego check
    ports:
    - containerPort: 80
```
and this `kustomization.yaml` 

```
resources:
  - simple-pod.yaml
```
Since I have all my policies in the `policy` folder I updated the `kubernetes.rego` to : 
```
# package lib.kubernetes
package policy.kubernetes
```
and the `security.rego` to:
```
# import data.lib.kubernetes
import data.policy.kubernetes
```
Then ran : `kustomize build | conftest test *.yaml --combine -` to render the yaml files the same way flux does. I expect a failure since I am using the `default` namespace and `latest` tag on the image but seeing the same result:
```
k8s-repo/kubernetes-security-policies$ kustomize build | conftest test *.yaml --combine -

20 tests, 20 passed, 0 warnings, 0 failures, 0 exceptions
```

It seems like perhaps the `kubernetes.rego` might need to be touched up in order to read flux. I would appreciate some feeback. 
Thanks.
